#server:
#    port: 8888
#spring:
#    profiles:
#        active: native

server:
    port: 8899
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Pavucsan/config-store
                    search-paths:
                        - '*service'